/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module br1_opt(i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, f);
  output f;
  input i0;
  input i1;
  input i10;
  input i11;
  input i2;
  input i3;
  input i4;
  input i5;
  input i6;
  input i7;
  input i8;
  input i9;
  assign f = 1'h0;
endmodule
