/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module rd84_opt(i0, i1, i2, i3, i4, i5, i6, i7, f);
  output f;
  input i0;
  input i1;
  input i2;
  input i3;
  input i4;
  input i5;
  input i6;
  input i7;
  assign f = 1'h0;
endmodule
