// Generated by reproduce_paper_full (SMABC method)
module ex1010_opt(i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, f);
input i0;
input i1;
input i2;
input i3;
input i4;
input i5;
input i6;
input i7;
input i8;
input i9;
output f;
wire t0;
assign t0 = ~i6 & ~i5 & ~i4 & ~i3 & ~i2 & ~i1 & ~i0;
assign f = t0;
endmodule
