// Generated by reproduce_paper_full (SMABC method)
module rd84_opt(i0, i1, i2, i3, i4, i5, i6, i7, f);
input i0;
input i1;
input i2;
input i3;
input i4;
input i5;
input i6;
input i7;
output f;
wire t0;
wire t1;
wire t2;
assign t0 = ~i7 & ~i3 & ~i2 & ~i1 & ~i0;
assign t1 = ~i6 & ~i3 & ~i2 & ~i1 & ~i0;
assign t2 = i5 & ~i3 & ~i2 & ~i1 & ~i0;
assign f = t0 ^ t1 ^ t2;
endmodule
